name: Publish Packages

on:
  release:
    types: [published]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          
      - run: npm install
      
      - run: echo "@itsidleboy:registry=https://npm.pkg.github.com" >> .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc
      - run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          jq --arg name "@itsidleboy/$PACKAGE_NAME" '.name = $name' package.json > temp.json && mv temp.json package.json

      - run: npm publish --registry=https://npm.pkg.github.com/ --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          
      - run: npm install
      - run: npm publish --registry=https://registry.npmjs.org/ --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}